title: "francisco [frahn•SEE•shkoo]" # name of the site
author: francisco ferreira # name of site's author
email: franciscopauloferreira@gmail.com # email of site's author
url: https://fpsdf.github.io # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  Francisco's personal page.

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "francisco ↩" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page
  lowercase_titles: true # show titles in lowercase in lists

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jektex

jektex:
  cache_dir: ".jektex-cache"
  ignore: ["*.xml"]
  silent: false
  macros:
    - ["\\Q", "\\mathbb{Q}"]
    - ["\\C", "\\mathbb{C}"]

exclude:
  - .jektex-cache/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

collections:
  projects:
    output: true
    permalink: /projects/:slug.html

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

goat_counter: fpsdf

# Development settings
livereload: true
